version: '3.3'

x-environment: &environment
  environment:
    MARIADB_USER: drupal
    MARIADB_PASSWORD: drupal
    MARIADB_DATABASE: drupal
    MARIADB_HOST: mariadb
    MARIADB_ROOT_PASSWORD: drupal
    QUANT_ENVIRONMENT_TYPE: local
    APACHE_RUN_USER: nobody
    DRUPAL_REVALIDATE_SECRET: secret
    DRUPAL_PREVIEW_SECRET: secret
    NEXT_PUBLIC_DRUPAL_BASE_URL: "http://drupal"
    NEXT_PUBLIC_IMAGE_DOMAIN: "http://localhost:81"
    REDIS_HOST: redis

services:
  drupal:
    build:
      context: .
      dockerfile: ./Dockerfile-drupal
    depends_on:
      - mariadb
      - redis
    ports:
      - "81:80"
    <<: *environment
    volumes:
      - ./src-drupal:/opt/drupal

  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile-nextjs
      args:
        NEXT_PUBLIC_DRUPAL_BASE_URL: "http://drupal"
    depends_on:
      - drupal
    <<: *environment
    ports:
      - "80:3000"
    volumes:
    - ./src-nextjs/tsconfig.json:/app/tsconfig.json
    - ./src-nextjs/tailwind.config.js:/app/tailwind.config.js
    - ./src-nextjs/styles:/app/styles
    - ./src-nextjs/postcss.config.js:/app/postcss.config.js
    - ./src-nextjs/lib:/app/lib
    - ./src-nextjs/components:/app/components
    - ./src-nextjs/pages:/app/pages
    - ./src-nextjs/public:/app/public
    - ./src-nextjs/next-env.d.ts:/app/next-env.d.ts
    - ./src-nextjs/next.config.js:/app/next.config.js

  mariadb:
    image: mariadb:latest
    <<: *environment

  redis:
    image: redis
