version: '3.3'

x-environment: &environment
  environment:
    MARIADB_USER: drupal
    MARIADB_PASSWORD: drupal
    MARIADB_DATABASE: drupal
    MARIADB_HOST: mariadb
    MARIADB_ROOT_PASSWORD: drupal
    QUANT_ENVIRONMENT_TYPE: local
    APACHE_RUN_USER: nobody
    DRUPAL_REVALIDATE_SECRET: secret
    DRUPAL_PREVIEW_SECRET: secret
    NEXT_PUBLIC_DRUPAL_BASE_URL: "http://drupal"
    NEXT_IMAGE_DOMAIN: "localhost"

services:
  drupal:
    build:
      context: .
      dockerfile: ./Dockerfile-drupal
    depends_on:
      - mariadb
      - redis
    ports:
      - "81:80"
    <<: *environment
    volumes:
      - ./src-drupal:/opt/drupal

  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile-nextjs
    depends_on:
      - drupal
    <<: *environment
    ports:
      - "80:3000"
    #volumes:
    #  - ./src-nextjs:/app

  mariadb:
    image: mariadb:latest
    <<: *environment

  redis:
    image: redis
