FROM node:18-alpine

## TEST
RUN apk add vim curl

WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY src-nextjs/ /app/
RUN chown -R nextjs /app

USER nextjs

## Test install as nextjs user.
RUN npm install --production

EXPOSE 3000

ENV PORT 3000

CMD ["/bin/sh", "-c", "npm run build; npm start"]
