FROM node:18-alpine

ARG NEXT_PUBLIC_DRUPAL_BASE_URL
ENV NEXT_PUBLIC_DRUPAL_BASE_URL=${NEXT_PUBLIC_DRUPAL_BASE_URL}

## TEST
RUN apk add vim curl

WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY src-nextjs/ /app/
RUN chown -R nextjs /app

USER nextjs
RUN npm install

EXPOSE 3000
ENV PORT 3000

COPY --from=ghcr.io/quantcdn/entrypoint-node:main /usr/local/bin/entrypoint-node /usr/bin/entrypoint-node
CMD [ "/usr/bin/entrypoint-node", "build", "start" ]
