FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY src-nextjs/package.json src-nextjs/package-lock.json ./
RUN  npm install --production

FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

## TEST
RUN apk add vim curl

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json
COPY src-nextjs/ /app/

RUN chown -R nextjs /app

USER nextjs

## Test install as nextjs user.
RUN npm install --production

EXPOSE 3000

ENV PORT 3000

CMD ["/bin/sh", "-c", "npm run build; npm start"]
