apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream
  namespace: default
  labels:
    app: ingress-upstream
spec:
    ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
        app: nextjs
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}