version: '3.6' 
services:
  nextjs:
    container_name: ddev-${DDEV_SITENAME}-nextjs
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile-nextjs
    depends_on:
      - web
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: nextjs
      com.ddev.approot: $DDEV_APPROOT
    environment:
      NEXT_PUBLIC_DRUPAL_BASE_URL: http://web
      NEXT_PUBLIC_IMAGE_DOMAIN: http://web
      NEXT_PUBLIC_BASE_URL: http://web
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 9998:3000
      HTTPS_EXPOSE: 9999:3000