name: Schedule tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  scheduled_tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: quantcdn/cloud-init-action@v1.0.0
        env:
          SECTION_K8S_API_URL: "${{ secrets.SECTION_K8S_API_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"

      - name: Run the scheduled task
        env:
          KUBECONFIG: # unset
        run: |
          kubectl exec deploy/drupal-nextjs-main --container=drupal-main -- /opt/deployment-scripts/cron.sh
