name: Schedule tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  scheduled_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "SECTION_K8S_API_URL=${{ secrets.SECTION_K8S_API_URL }}" >> "$GITHUB_ENV"
            echo "SECTION_API_TOKEN=${{ secrets.SECTION_K8S_API_URL }}" >> "$GITHUB_ENV"
          else
            echo "** Cron schedule only runs on master branch"
            exit 1
          fi
      - name: Setup kubeconfig
        run: |
          ./ci/init-kube.sh

      - name: Run the scheduled task
        run: |
          kubectl exec deploy/drupal -- /opt/deployment-scripts/cron.sh
