name: Schedule tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  scheduled_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set environment for branch
        run: |
          echo "SECTION_K8S_API_URL=${{ secrets.SECTION_K8S_API_URL_PROD }}" >> "$GITHUB_ENV"
          echo "SECTION_API_TOKEN=${{ secrets.SECTION_API_TOKEN_PROD }}" >> "$GITHUB_ENV"
      - name: Setup kubeconfig
        run: |
          ./ci/init-kube.sh

      - name: Run the scheduled task
        run: |
          kubectl exec deploy/drupal --container=drupal -- /opt/deployment-scripts/cron.sh
