name: Database backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        env:
          SECTION_K8S_API_URL: "${{ secrets.SECTION_K8S_API_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"
        run: |
          ./ci/init-kube.sh

      - name: Prepare backup location
        run: |
          echo "dir=backups" >> $GITHUB_OUTPUT
          echo "file=backup-$(date +'%Y-%m-%d').sql" >> $GITHUB_OUTPUT
        id: backup  # this is used on variable path

      - name: Run the database backup
        env:
          KUBECONFIG: # Unset
          FILENAME: ${{ steps.backup.outputs.file }}
          DIR: ${{ steps.backup.outputs.dir }}
        run: |
          mkdir -p $DIR
          kubectl exec deploy/drupal --container=drupal -- drush sql:dump > $DIR/$FILENAME

      - uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: ${{ steps.backup.outputs.dir }}/${{ steps.backup.outputs.file }}
