name: Run command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'The command to run in Quant Cloud (e.g "drush cr")'
        required: true

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create friendly branch name
        id: setup-branch-names
        run: |
          BRANCH_NAME=`echo ${GITHUB_REF##*/} | tr "[:upper:]" "[:lower:]" | sed "s/[^[:alnum:]-]//g"`
          echo $BRANCH_NAME
          echo "BRANCH_NAME_CLEAN=$(echo $BRANCH_NAME)" >> $GITHUB_ENV

      - name: Setup kubeconfig
        env:
          SECTION_K8S_API_URL: "${{ secrets.SECTION_K8S_API_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"
        run: |
          ./ci/init-kube.sh

      - name: Run the command
        env:
          KUBECONFIG: # Unset
        run: |
          kubectl exec deploy/drupal-nextjs-${{ env.BRANCH_NAME_CLEAN }} --container=drupal-${{ env.BRANCH_NAME_CLEAN }} -- ${{ github.event.inputs.command }}
